# ── Patient Demographics Variable Definitions ──
# column: actual PostgreSQL column name in patient_demographics
# column=None: calculated via JOIN to another table (see analytics/utils.py)

DEMOGRAPHICS_VARIABLES = [
    {
        "id":       "A.1",
        "name":     "FIRST_NAME",
        "column":   "first_name",
        "required": True,
        "desc":     "Patient first name",
    },
    {
        "id":       "A.2",
        "name":     "LAST_NAME",
        "column":   "last_name",
        "required": True,
        "desc":     "Patient last name",
    },
    {
        "id":       "A.3",
        "name":     "DATE_OF_BIRTH",
        "column":   "date_of_birth",
        "required": True,
        "desc":     "Date of birth",
    },
    {
        "id":       "A.4",
        "name":     "DATE_OF_DEATH",
        "column":   "date_of_death",
        "required": False,
        "desc":     "Date of death",
    },
    {
        "id":       "A.5",
        "name":     "CAUSE_OF_DEATH",
        "column":   "cause_of_death",
        "required": False,
        "desc":     "Cause of death",
    },
    {
        "id":       "A.6",
        "name":     "GENDER",
        "column":   "gender",
        "required": True,
        "desc":     "Gender",
    },
    {
        "id":       "A.7",
        "name":     "ETHNICITY",
        "column":   "ethnicity_id",
        "required": True,
        "desc":     "Ethnic origin",
    },
    {
        "id":       "A.8",
        "name":     "NATIONALITY",
        "column":   "nationality_id",
        "required": True,
        "desc":     "Nationality",
    },
    {
        "id":       "A.9",
        "name":     "EMAIL_ADDRESS",
        "column":   "email_address",
        "required": False,
        "desc":     "Email address (excluding placeholder/default emails)",
    },
    {
        "id":       "A.10",
        "name":     "DIAGNOSIS",
        "column":   None,
        "required": True,
        "desc":     "Patient must have at least one record in patient_diagnoses",
    },
    {
        "id":       "A.11",
        "name":     "NHS_NUMBER",
        "column":   None,
        "required": True,
        "desc":     "NHS number must exist in patient_numbers",
    },
]

# ── Default / placeholder emails to treat as missing ──
DEFAULT_EMAILS = [
    "renal@radar.org",
    "noemailaddress@radar.radar",
    "radar@radar.com",
    "radar@radar.co.uk",
    "spond@radar.org",
    "blee@radar.org",
    "bpatient@radar.org",
    "radar@radar.nhs.uk",
    "radar@chagwell.com",
    "babshir@radar.org",
    "gwoodman@radar.org",
    "noemail@radar.radar",
    "cfletcher@radar.org",
    "srosser@radar.org",
    "sshaw@radar.org",
    "nocontactplease@radar.radar",
    "lbroadhead@radar.org",
    "vbennett@radar.org",
    "radar@radar.nhs",
    "patient@radar.org",
    "rcook@radar.org",
    "nina-hewitson@gmail.comradar@radar.radar",
    "awelsby@radar.org",
    "jhellerman@radar.org",
    "mchaudhary@radar.org",
    "radar@radar.org",
    "zhirsch@radar.org",
    "nfowkes@radar.org",
    "msnell@radar.org",
    "sjennings@radar.org",
    "radar@radar.rad",
    "gcollyer@radar.org",
    "zkassam@radar.org",
    "jbooth@radar.org",
    "radar@radar.radar",
    "smiradarr@hotmail.co.uk",
    "ls@radar.org",
    "denglish@radar.org",
    "withdrawn@radar.radar",
    "hunterbarbara@radar.org",
    "gfletcher@radar.org",
    "jmarshall@radar.org",
    "deceased@radar.radar",
    "jglover@radar.org",
    "radar@radar.uk",
    "jdenton@radar.org",
    "dsever@radar.org",
]
